---
# Docker Trusted Registry
dtr:
  nodes:
    - 
      name: cedatt

# Universal Control Plane
ucp:
  nodes:
    -
      name: gideon
      type: controller
    -
      name: harkon
      type: controller
    -
      name: caffon
      type: controller
    -
      name: raklin
    -
      name: zaulin
    -
      name: harlin
