---
gitlabci:
  #  token: xxxxxxxxxxxxxxxxxxxx
  name: Demo Override
  tags:
    - toto
    - tata
    - ucp

dtr:
  nodes:
    - 
      name: cedatt
ucp:
  nodes:
    -
      name: gideon
      type: controller
    -
      name: hark
      type: controller
    -
      name: caff
      type: controller
    -
      name: ranklin
    -
      name: zaul
    -
      name: harlon



