version: "2"

services:
  voting-app:
    image: dockercond2/dockercon-voting-app
    ports:
       - "5000:80"

  redis:
    image: redis
    ports: ["6379"]

  worker:
    image: dockercond2/dockercon-worker

  db:
    image: postgres:9.4

  result-app:
    image: dockercond2/dockercon-result-app
    ports:
       - "5001:80"

